export const LOGIN_REQUEST = 'LOGIN_REQUEST'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_FAIL = 'LOGIN_FAIL'
export const LOGIN_OUT = 'LOGIN_OUT'

export const SIGNUP_REQUEST = 'SIGNUP_REQUEST'
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS'
export const SIGNUP_FAIL = 'SIGNUP_FAIL'

export const PROGRESS_BAR_PROGRESSING = 'PROGRESS_BAR_PROGRESSING'
export const PROGRESS_BAR_DONE = 'PROGRESS_BAR_DONE'

export const LEFT_MENU_TOGGLE = 'LEFT_MENU_TOGGLE'
export const MASK_TOGGLE = 'MASK_TOGGLE'

export const LOGO_UP = 'LOGO_UP'
export const LOGO_DOWN = 'LOGO_DOWN'
export const NAV_BAR_SHADOW = 'NAV_BAR_SHADOW'
export const NAV_BAR_SHADOW_HIDE = 'NAV_BAR_SHADOW_HIDE'
export const PROFILE_MENU_OPEN = 'PROFILE_MENU_OPEN'
export const PROFILE_MENU_CLOSE = 'PROFILE_MENU_CLOSE'
export const SCROLL_BUTTON_SHOW = 'SCROLL_BUTTON_SHOW'
export const SCROLL_BUTTON_HIDE = 'SCROLL_BUTTON_HIDE'
